sudo: required
language: bash
cache:
  directories:
  - ${HOME}/.ivy2
  - ${HOME}/.m2
  - ${HOME}/.sbt
services: docker
env:
  global:
  - TERRAFORM_VERSION=0.9.6
  - AWSCLI_VERSION=1.11.*
  - DOCKER_COMPOSE_VERSION=1.13.*
  - GT_CHATTA_SETTINGS_BUCKET=geotrellis-site-production-config-us-east-1
  - AWS_DEFAULT_REGION=us-east-1
  - secure: T4Wgz/5ZiqIKOh6kxxeCHMwfqPZGn/5zsuCPz+4qdESQvsiuKqVZ1XtagZG5F8Q49ztrdvxWJmCAWZjuuHSRID28mzTgpGe2X1RrQd4D0AW/I9ajLoy57dymxp4AaSWgr0DcaPqRPzlHwmEj2EEYD+jegg50lfHD3R5JlUKlJ+w=
  - secure: Cstj/BLZCU1+jVuG2WwYDDD8noeoLQ53WlT5z8AW0YTqdwhFArN2WoBozp1mE/W7mr+rCE+brYAQoSsozRjMp9PYzKb4tdGlFGrodyZHoVWVFW///GUPb8oVpindCsyFC+aN0Q8M8MUP2C61GE5UqosS3+iDUQhX1c0O8NHXPEs=
  - secure: AaGydeuJdzzyFSCQW/m3vXGfwdm6JMmTIP8mVI3OoIo+ZFnGoMra4pHBEg5X13gnujGvwTFMQ85TREm9FSLb1RN5QdGRi9p6zcfS9rNvRp2CzFxfazV4QONFmwxC6gTVIQA98Ni51SFoM9yt3umlUDWoedyn9ShGaPt6jTdqxHU=
  - secure: WHV8Lxl7jnVsGMgXju/BSAUkNesDUC1UKqH5kYk5aAnpdCf6YQaFqc7oVvCnymKJx32A3YN9lhhXO5rqhQB9UPff8W4U/cNHrgksbVxj/rQHj2nRj1hb/sXlXxySU/bRb9l4OnbEHIxNExVHiBtrL8T+xFy9dzYCWpYD3rmXT+c=
script:
- mkdir -p ~/.local/bin
- export PATH="~/.local/bin:$PATH"
- pip install --user docker-compose==${DOCKER_COMPOSE_VERSION}
- scripts/cibuild
before_deploy:
- wget -O terraform-${TERRAFORM_VERSION}.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
- unzip -d ~/.local/bin terraform-${TERRAFORM_VERSION}.zip
- pip install --user awscli==${AWSCLI_VERSION}
- rm terraform-${TERRAFORM_VERSION}.zip
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy
  on:
    branch: master
after_deploy:
- rm deployment/terraform/${GT_CHATTA_SETTINGS_BUCKET}.tfplan
